### ISSUE TITLE
Yield problem whith ..byId functions

### ISSUE THREAD

**Issue by NiotoMOto** [t3chnoboy/koa-mongo-rest#10]
Hi,

At fist thans for this repo.

I have problems with the actions functions, when I call routes ressouces/:id i have in the related action function 

`You may only yield a function, promise, generator, array, or object, but the following object was passed: "55af8ca1baedabac1b10b075"`
For exemple https://github.com/t3chnoboy/koa-mongo-rest/blob/master/lib/actions.js#L26.
I dont understand this line by the way.

I do something wrong ?

**Comment by NiotoMOto** [comment]
I am sorry, i used koa-route and in differents way. So I switch to koa-router and its works.
However with the last version 5.1.2 of  koa-router  I have to change the routes file 

```
var router = require('koa-router')();
router.get(prefix + ("/" + modelName), actions.findAll);
router.get(prefix + ("/" + modelName + "/:id"), actions.findById);
...

app.use(router.routes());
```

It works but it is good pratice ?

**Comment by tomaash** [comment]
Looks good to me..

**Comment by NiotoMOto** [comment]
Ok thanks and sorry for the fake issue
