### ISSUE TITLE
About enhancing method 'findAll'

### ISSUE THREAD

**Issue by wentingliu** [t3chnoboy/koa-mongo-rest#3]
I just stole the code of https://github.com/adamjacobbecker/mongoose-api-query and used it to enhance `findAll`. Is it appropriate for integrating `mongoose-api-query` to `koa-mongo-rest`? If you thinks so, I may convert the code to coffeescript, then submit to your repo.

**Comment by tomaash** [comment]
We've decided to go with a different approach, compatible with https://github.com/wprl/baucis
