### ISSUE TITLE
Unable to run example. Gives error -  app.use() requires a generator function

### ISSUE THREAD

**Issue by explorer2309** [t3chnoboy/koa-mongo-rest#9]
I am running the example, with a simple modification in require koa-mongo-rest

``` javascript
koa = require('koa');
router = require('koa-router');
generateApi = require('koa-mongo-rest');

mongoUrl = '127.0.0.1:27017';
mongoose = require('mongoose');
mongoose.connect(mongoUrl);

schema = new mongoose.Schema({
  email: String,
  name: String,
  password: String,
  address: String,
  zipcode: Number,
  lists: Array
});

app = koa();
app.use(router(app));

model = mongoose.model('user', schema);
generateApi(app, model, '/api');

app.listen(process.env.PORT || 5000);
```

It gives me this error:
C:\del\mongotest>npm start

> mongotest@1.0.0 start C:\del\mongotest
> node --harmony app.js

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: app.use() requires a generator function
    at Application.app.use (C:\del\mongotest\node_modules\koa\lib\application.js:100:5)
    at Object.<anonymous> (C:\del\mongotest\app.js:19:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! mongotest@1.0.0 start: `node --harmony app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mongotest@1.0.0 start script 'node --harmony app.js'.
npm ERR! This is most likely a problem with the mongotest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mongotest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\del\mongotest\npm-debug.log

**Comment by tomaash** [comment]
Try this:

``` js
var router = require('koa-router')();
generateApi(router, model, '/api');
app
  .use(router.routes())
  .use(router.allowedMethods());
```

**Comment by explorer2309** [comment]
The router object does not have the routes() and .allowedMethods() methods.

Perhaps, I am seeing the problem because I am using later versions of node modules. This is what I have:
    "koa": "^0.21.0",
    "koa-mongo-rest": "^0.3.4",
    "koa-router": "^5.1.2",
    "mongoose": "^4.0.6"

**Comment by tomaash** [comment]
Is your router object executed like this?  `router = require('koa-router')()`

**Comment by explorer2309** [comment]
Yes.

console.dir on the router object gives

{ opts: {},
  methods: [ 'HEAD', 'OPTIONS', 'GET', 'PUT', 'PATCH', 'POST', 'DELETE' ],
  params: {},
  stack: [] }

**Comment by tomaash** [comment]
It's on the prototype:

``` js
console.dir(Object.getPrototypeOf(router));
{ checkout: [Function],
  connect: [Function],
  copy: [Function],
  delete: [Function],
  routes: [Function],
...
}
```

**Comment by explorer2309** [comment]
Apolologies! I have been super thick

For whatever reason I had written app.routes() instead of router.routes()

Sorry for taking your time :(
